I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 22, in script
    "Gzzz!"
IOError: Couldn't find file 'illurock.opus'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\Vargas\Downloads\Programs\renpy-6.99.12.4-sdk\renpy\bootstrap.py", line 305, in bootstrap
    renpy.main.main()
  File "C:\Users\Vargas\Downloads\Programs\renpy-6.99.12.4-sdk\renpy\main.py", line 499, in main
    run(restart)
  File "C:\Users\Vargas\Downloads\Programs\renpy-6.99.12.4-sdk\renpy\main.py", line 147, in run
    renpy.execution.run_context(True)
  File "C:\Users\Vargas\Downloads\Programs\renpy-6.99.12.4-sdk\renpy\execution.py", line 795, in run_context
    context.run()
  File "game/script.rpy", line 22, in script
    "Gzzz!"
  File "C:\Users\Vargas\Downloads\Programs\renpy-6.99.12.4-sdk\renpy\ast.py", line 624, in execute
    renpy.exports.say(who, what, interact=self.interact, *args, **kwargs)
  File "C:\Users\Vargas\Downloads\Programs\renpy-6.99.12.4-sdk\renpy\exports.py", line 1173, in say
    who(what, *args, **kwargs)
  File "C:\Users\Vargas\Downloads\Programs\renpy-6.99.12.4-sdk\renpy\character.py", line 911, in __call__
    self.do_display(who, what, cb_args=self.cb_args, **display_args)
  File "C:\Users\Vargas\Downloads\Programs\renpy-6.99.12.4-sdk\renpy\character.py", line 747, in do_display
    **display_args)
  File "C:\Users\Vargas\Downloads\Programs\renpy-6.99.12.4-sdk\renpy\character.py", line 523, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "C:\Users\Vargas\Downloads\Programs\renpy-6.99.12.4-sdk\renpy\ui.py", line 287, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\Vargas\Downloads\Programs\renpy-6.99.12.4-sdk\renpy\display\core.py", line 2553, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "C:\Users\Vargas\Downloads\Programs\renpy-6.99.12.4-sdk\renpy\display\core.py", line 3104, in interact_core
    renpy.audio.audio.periodic()
  File "C:\Users\Vargas\Downloads\Programs\renpy-6.99.12.4-sdk\renpy\audio\audio.py", line 960, in periodic_thread_main
    periodic_pass()
  File "C:\Users\Vargas\Downloads\Programs\renpy-6.99.12.4-sdk\renpy\audio\audio.py", line 917, in periodic_pass
    c.periodic()
  File "C:\Users\Vargas\Downloads\Programs\renpy-6.99.12.4-sdk\renpy\audio\audio.py", line 409, in periodic
    topf = load(self.file_prefix + filename + self.file_suffix)
  File "C:\Users\Vargas\Downloads\Programs\renpy-6.99.12.4-sdk\renpy\audio\audio.py", line 69, in load
    rv = renpy.loader.load(fn)
  File "C:\Users\Vargas\Downloads\Programs\renpy-6.99.12.4-sdk\renpy\loader.py", line 548, in load
    raise IOError("Couldn't find file '%s'." % name)
IOError: Couldn't find file 'illurock.opus'.

Windows-8-6.2.9200
Ren'Py 6.99.13.2919
Visual Novel IDE 1.0
